services:
  - type: web
    name: flash-flashcards
    env: python
    buildCommand: pip install -r requirements.txt && mkdir -p database
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: flashcards-data
      mountPath: /opt/render/project/src/database
      sizeGB: 1
